config/routes.rb
Rails.application.routes.draw do
  root 'publicacions#index'
  resources :publicacions

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/publicacion.rb
class Publicacion < ApplicationRecord
    validates :titulo, presence: true, length: { minimum: 5 }
    validates :body, presence: true
    has_one_attached :imagen
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/publicacions_controller.rb
class PublicacionsController < ApplicationController
  before_action :set_publicacion, only: [:edit, :update, :destroy]

  def index
    @publicacions = Publicacion.all
  end

  def new
    @publicacion = Publicacion.new
  end

  def edit
  end

  def create
    @publicacion = Publicacion.new(publicacion_params)
  
    if @publicacion.save
      redirect_to publicacions_path, notice: 'Publicación creada con éxito.'
    else
      render :new
    end
  end

  def update
    if @publicacion.update(publicacion_params)
      redirect_to publicacions_path, notice: 'Publicación actualizada con éxito.'
    else
      render :edit
    end
  end

  def destroy
    @publicacion.destroy
    redirect_to publicacions_url, notice: 'Publicación eliminada con éxito.'
  end

  private
    def set_publicacion
      @publicacion = Publicacion.find(params[:id])
    end

    def publicacion_params
      params.require(:publicacion).permit(:titulo, :body, :imagen)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TuAplicacion</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.3/zephyr/bootstrap.rtl.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/publicacions/edit.html.erb
<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
  <div class="card mt-3" style="width: 26rem;">
    <div class="card-body">
      <%= form_with(model: @publicacion, local: true, html: { class: 'needs-validation', novalidate: '' }) do |form| %>
        <% if @publicacion.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading"><%= pluralize(@publicacion.errors.count, "error") %> prohibited this publicacion from being saved:</h4>
            <ul>
            <% @publicacion.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :titulo, class: 'form-label' %>
          <%= form.text_field :titulo, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :body, class: 'form-label' %>
          <%= form.text_area :body, class: 'form-control' %>
        </div>
        
        <div class="form-group">
        <%= form.label :imagen, class: 'form-label' %>
        <%= form.file_field :imagen, class: 'form-control-file', onchange: 'loadFile(event)' %>
        <img id="output" style="max-width: 50px; max-height: 50px;"/>
      </div>
        <div class="actions">
          <%= form.submit class: 'btn btn-primary' %>
        </div>
        <div class="actions">
          <%= link_to 'Volver', publicacions_path, class: 'btn btn-secondary mt-3' %>
        <div>
      <% end %>
    </div>
  </div>  
</div>

app/views/publicacions/index.html.erb
<div class="container">
  <h1>Publicaciones</h1>

  <%= link_to 'Nueva Publicación', new_publicacion_path, class: 'btn btn-primary' %>

  <% @publicacions.each do |publicacion| %>
    <div class="card mt-3">
      <div class="card-body">
        <h2 class="card-title"><%= publicacion.titulo %></h2>
        <% if publicacion.imagen.attached? %>
          <%= image_tag publicacion.imagen, class: 'img-fluid', style: 'max-width: 500px; max-height: 500px;' %>
        <% end %>
        <p><%= publicacion.body %></p>
        <div class="d-flex flex-column align-items-end"> 
          <%= link_to 'Modificar', edit_publicacion_path(publicacion), class: 'btn btn-warning mb-2' %> 
          <%= button_to 'Eliminar', publicacion, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger' %> 
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/publicacions/new.html.erb
<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
  <div class="card mt-3">
    <div class="card-body">
      <%= form_with(model: @publicacion, local: true) do |form| %>
      
        <div class="field">
          <%= form.label :titulo %>
          <%= form.text_field :titulo, class: 'form-control' %>
          <% if @publicacion.errors.full_messages_for(:titulo).any? %>
            <div class="alert alert-danger mt-2">
              <%= @publicacion.errors.full_messages_for(:titulo).join(', ') %>
            </div>
          <% end %>
        </div>
      
        <div class="field">
          <%= form.label :body %>
          <%= form.text_area :body, class: 'form-control' %>
          <% if @publicacion.errors.full_messages_for(:body).any? %>
            <div class="alert alert-danger mt-2">
              <%= @publicacion.errors.full_messages_for(:body).join(', ') %>
            </div>
          <% end %>
        </div>

        <div class="field">
          <%= form.label :imagen %>
          <%= form.file_field :imagen, class: 'form-control-file' %>
          <% if @publicacion.errors.full_messages_for(:imagen).any? %>
            <div class="alert alert-danger mt-2">
              <%= @publicacion.errors.full_messages_for(:imagen).join(', ') %>
            </div>
          <% end %>
        </div>
      
        <div class="actions mt-3">
          <%= form.submit class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="container mt-3">
  <%= link_to 'Volver', publicacions_path, class: 'btn btn-secondary' %>
</div>